services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    volumes:
      - ./backend/models:/app/models
      - ./backend/logs:/app/logs
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - frontend/.env.docker
    # volumes:
    #   - ./frontend:/app
    expose:
      - "5173"
    depends_on:
      - backend
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    env_file:
      - caddy/.env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  frontend_node_modules:
  caddy_data:
  caddy_config:
