[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.4.1",
    "ddgs>=9.11.2",
    "deepagents>=0.4.5",
    "duckduckgo-search>=8.1.1",
    "fastapi>=0.135.1",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.17",
    "langchain-openai>=1.1.10",
    "langgraph>=1.0.10",
    "langgraph-checkpoint-postgres>=3.0.4",
    "numpy>=2.4.2",
    "openai-whisper>=20250625",
    "psycopg[binary,pool]>=3.3.3",
    "pyttsx3>=2.99",
    "pymupdf>=1.27.1",
    "pypdf>=6.7.5",
    "python-dotenv>=1.2.2",
    "semanticscholar>=0.11.0",
    "uvicorn>=0.41.0",
]
